****************************************************************;
******        HP TREE (PROC HPSPLIT) SCORING CODE        ******;
****************************************************************;
 
******              LABELS FOR NEW VARIABLES              ******;
LABEL _Node_ = 'Node number';
LABEL _Leaf_ = 'Leaf number';
LABEL _WARN_ = 'Warnings';
LABEL P_BAD0 = 'Predicted: BAD=0';
LABEL P_BAD1 = 'Predicted: BAD=1';
LABEL V_BAD0 = 'Validated: BAD=0';
LABEL V_BAD1 = 'Validated: BAD=1';
 
 _WARN_ = ' ';
 
******      TEMPORARY VARIABLES FOR FORMATTED VALUES      ******;
LENGTH _RT_5_6 $6;
_RT_5_6 = ' ';
DROP _RT_5_6;
_RT_5_6 = LEFT(TRIM(PUT(JOB, $6.)));
 
******             ASSIGN OBSERVATION TO NODE             ******;
IF NOT MISSING(DEBTINC) AND ((DEBTINC >= 43.84338265478))
 THEN DO;
  IF NOT MISSING(CLAGE) AND ((CLAGE >= 222.358612846148))
   THEN DO;
    IF NOT MISSING(DEBTINC) AND ((DEBTINC >= 46.710400330072))
     THEN DO;
      _Node_ = 10;
      _Leaf_ = 2;
      P_BAD0 = 0;
      P_BAD1 = 1;
      V_BAD0 = 0;
      V_BAD1 = 1;
    END;
    ELSE DO;
      IF NOT MISSING(JOB) AND (_RT_5_6 IN ('ProfEx') )
       THEN DO;
        _Node_ = 16;
        _Leaf_ = 6;
        P_BAD0 = 0;
        P_BAD1 = 1;
        V_BAD0 = .;
        V_BAD1 = .;
      END;
      ELSE DO;
        _Node_ = 15;
        _Leaf_ = 5;
        P_BAD0 = 1;
        P_BAD1 = 0;
        V_BAD0 = 1;
        V_BAD1 = 0;
      END;
  END;
END;
ELSE DO;
  _Node_ = 5;
  _Leaf_ = 1;
  P_BAD0 = 0;
  P_BAD1 = 1;
  V_BAD0 = 0.1;
  V_BAD1 = 0.9;
END;
END;
ELSE DO;
IF NOT MISSING(DELINQ) AND ((DELINQ >= 4.100000000000001))
 THEN DO;
  _Node_ = 4;
  _Leaf_ = 0;
  P_BAD0 = 0;
  P_BAD1 = 1;
  V_BAD0 = 0;
  V_BAD1 = 1;
END;
ELSE DO;
  IF NOT MISSING(DEROG) AND ((DEROG >= 1.1))
   THEN DO;
    IF NOT MISSING(CLNO) AND ((CLNO >= 30.08))
     THEN DO;
      _Node_ = 14;
      _Leaf_ = 4;
      P_BAD0 = 0;
      P_BAD1 = 1;
      V_BAD0 = 0;
      V_BAD1 = 1;
    END;
    ELSE DO;
      IF NOT MISSING(CLNO) AND ((CLNO < 16.64))
       THEN DO;
        IF NOT MISSING(CLAGE) AND ((CLAGE >= 234.03608134064))
         THEN DO;
          _Node_ = 26;
          _Leaf_ = 8;
          P_BAD0 = 1;
          P_BAD1 = 0;
          V_BAD0 = 1;
          V_BAD1 = 0;
        END;
        ELSE DO;
          _Node_ = 25;
          _Leaf_ = 7;
          P_BAD0 = 0;
          P_BAD1 = 1;
          V_BAD0 = 0;
          V_BAD1 = 1;
        END;
      END;
      ELSE DO;
        IF NOT MISSING(NINQ) AND ((NINQ >= 4.03))
         THEN DO;
          _Node_ = 28;
          _Leaf_ = 9;
          P_BAD0 = 0;
          P_BAD1 = 1;
          V_BAD0 = 1;
          V_BAD1 = 0;
        END;
        ELSE DO;
          IF NOT MISSING(JOB) AND (_RT_5_6 IN ('Sales','Self') )
           THEN DO;
            IF NOT MISSING(CLAGE) AND ((CLAGE >= 140.616333384704))
             THEN DO;
              _Node_ = 52;
              _Leaf_ = 18;
              P_BAD0 = 1;
              P_BAD1 = 0;
              V_BAD0 = 1;
              V_BAD1 = 0;
            END;
            ELSE DO;
              _Node_ = 51;
              _Leaf_ = 17;
              P_BAD0 = 0;
              P_BAD1 = 1;
              V_BAD0 = .;
              V_BAD1 = .;
            END;
          END;
          ELSE DO;
            IF NOT MISSING(LOAN) AND ((LOAN < 6992))
             THEN DO;
              _Node_ = 49;
              _Leaf_ = 16;
              P_BAD0 = 0;
              P_BAD1 = 1;
              V_BAD0 = .;
              V_BAD1 = .;
            END;
            ELSE DO;
              IF NOT MISSING(MORTDUE) AND ((MORTDUE >= 111546.72))
               THEN DO;
                _Node_ = 68;
                _Leaf_ = 31;
                P_BAD0 = 0;
                P_BAD1 = 1;
                V_BAD0 = .;
                V_BAD1 = .;
              END;
              ELSE DO;
                _Node_ = 67;
                _Leaf_ = 30;
                P_BAD0 = 0.97222222;
                P_BAD1 = 0.027777778;
                V_BAD0 = 0.9;
                V_BAD1 = 0.1;
              END;
            END;
          END;
        END;
      END;
    END;
  END;
  ELSE DO;
    IF NOT MISSING(CLNO) AND ((CLNO < 2.56))
     THEN DO;
      _Node_ = 11;
      _Leaf_ = 3;
      P_BAD0 = 0;
      P_BAD1 = 1;
      V_BAD0 = .;
      V_BAD1 = .;
    END;
    ELSE DO;
      IF NOT MISSING(VALUE) AND ((VALUE < 50634.36))
       THEN DO;
        IF NOT MISSING(LOAN) AND ((LOAN < 6110))
         THEN DO;
          IF NOT MISSING(CLAGE) AND ((CLAGE < 23.841648439784))
           THEN DO;
            _Node_ = 29;
            _Leaf_ = 10;
            P_BAD0 = 1;
            P_BAD1 = 0;
            V_BAD0 = 1;
            V_BAD1 = 0;
          END;
          ELSE DO;
            IF NOT MISSING(CLAGE) AND ((CLAGE >= 163.971270373688))
             THEN DO;
              _Node_ = 40;
              _Leaf_ = 14;
              P_BAD0 = 1;
              P_BAD1 = 0;
              V_BAD0 = 1;
              V_BAD1 = 0;
            END;
            ELSE DO;
              _Node_ = 39;
              _Leaf_ = 13;
              P_BAD0 = 0;
              P_BAD1 = 1;
              V_BAD0 = 0;
              V_BAD1 = 1;
            END;
          END;
        END;
        ELSE DO;
          IF NOT MISSING(CLAGE) AND ((CLAGE >= 315.778360802084))
           THEN DO;
            _Node_ = 32;
            _Leaf_ = 11;
            P_BAD0 = 0;
            P_BAD1 = 1;
            V_BAD0 = .;
            V_BAD1 = .;
          END;
          ELSE DO;
            IF NOT MISSING(LOAN) AND ((LOAN < 13166))
             THEN DO;
              IF NOT MISSING(JOB) AND (_RT_5_6 IN ('ProfEx','Self') )
               THEN DO;
                _Node_ = 54;
                _Leaf_ = 19;
                P_BAD0 = 0;
                P_BAD1 = 1;
                V_BAD0 = 1;
                V_BAD1 = 0;
              END;
              ELSE DO;
                IF NOT MISSING(DELINQ) AND ((DELINQ >= 1.1))
                 THEN DO;
                  _Node_ = 70;
                  _Leaf_ = 33;
                  P_BAD0 = 0;
                  P_BAD1 = 1;
                  V_BAD0 = 0;
                  V_BAD1 = 1;
                END;
                ELSE DO;
                  _Node_ = 69;
                  _Leaf_ = 32;
                  P_BAD0 = 0.85714286;
                  P_BAD1 = 0.14285714;
                  V_BAD0 = 0.69565217;
                  V_BAD1 = 0.30434783;
                END;
              END;
            END;
            ELSE DO;
              IF NOT MISSING(DEROG) AND ((DEROG >= 0.1))
               THEN DO;
                IF NOT MISSING(DEBTINC) AND ((DEBTINC >= 33.808820791258))
                 THEN DO;
                  _Node_ = 72;
                  _Leaf_ = 35;
                  P_BAD0 = 0;
                  P_BAD1 = 1;
                  V_BAD0 = 1;
                  V_BAD1 = 0;
                END;
                ELSE DO;
                  _Node_ = 71;
                  _Leaf_ = 34;
                  P_BAD0 = 1;
                  P_BAD1 = 0;
                  V_BAD0 = 1;
                  V_BAD1 = 0;
                END;
              END;
              ELSE DO;
                _Node_ = 55;
                _Leaf_ = 20;
                P_BAD0 = 0.98630137;
                P_BAD1 = 0.01369863;
                V_BAD0 = 0.93333333;
                V_BAD1 = 0.066666667;
              END;
            END;
          END;
        END;
      END;
      ELSE DO;
        IF NOT MISSING(CLAGE) AND ((CLAGE < 47.196585428768))
         THEN DO;
          IF NOT MISSING(DEBTINC) AND ((DEBTINC < 36.67583846655))
           THEN DO;
            _Node_ = 33;
            _Leaf_ = 12;
            P_BAD0 = 0;
            P_BAD1 = 1;
            V_BAD0 = 0;
            V_BAD1 = 1;
          END;
          ELSE DO;
            IF NOT MISSING(JOB) AND (_RT_5_6 IN ('Mgr','Office') )
             THEN DO;
              _Node_ = 43;
              _Leaf_ = 15;
              P_BAD0 = 0;
              P_BAD1 = 1;
              V_BAD0 = .;
              V_BAD1 = .;
            END;
            ELSE DO;
              IF NOT MISSING(MORTDUE) AND ((MORTDUE < 24792.8))
               THEN DO;
                _Node_ = 57;
                _Leaf_ = 21;
                P_BAD0 = 0;
                P_BAD1 = 1;
                V_BAD0 = .;
                V_BAD1 = .;
              END;
              ELSE DO;
                _Node_ = 58;
                _Leaf_ = 22;
                P_BAD0 = 1;
                P_BAD1 = 0;
                V_BAD0 = 1;
                V_BAD1 = 0;
              END;
            END;
          END;
        END;
        ELSE DO;
          IF NOT MISSING(DELINQ) AND ((DELINQ >= 0.1))
           THEN DO;
            IF NOT MISSING(NINQ) AND ((NINQ >= 3.12))
             THEN DO;
              IF NOT MISSING(LOAN) AND ((LOAN >= 21986))
               THEN DO;
                _Node_ = 66;
                _Leaf_ = 29;
                P_BAD0 = 1;
                P_BAD1 = 0;
                V_BAD0 = 1;
                V_BAD1 = 0;
              END;
              ELSE DO;
                _Node_ = 65;
                _Leaf_ = 28;
                P_BAD0 = 0;
                P_BAD1 = 1;
                V_BAD0 = 0;
                V_BAD1 = 1;
              END;
            END;
            ELSE DO;
              IF NOT MISSING(DEBTINC) AND ((DEBTINC < 8.005661713629999))
               THEN DO;
                _Node_ = 63;
                _Leaf_ = 26;
                P_BAD0 = 0;
                P_BAD1 = 1;
                V_BAD0 = 0;
                V_BAD1 = 1;
              END;
              ELSE DO;
                _Node_ = 64;
                _Leaf_ = 27;
                P_BAD0 = 0.91637631;
                P_BAD1 = 0.083623693;
                V_BAD0 = 0.87218045;
                V_BAD1 = 0.12781955;
              END;
            END;
          END;
          ELSE DO;
            IF NOT MISSING(JOB) AND (_RT_5_6 IN ('Sales') )
             THEN DO;
              IF NOT MISSING(CLAGE) AND ((CLAGE < 105.583927901228))
               THEN DO;
                _Node_ = 61;
                _Leaf_ = 25;
                P_BAD0 = 0;
                P_BAD1 = 1;
                V_BAD0 = .;
                V_BAD1 = .;
              END;
              ELSE DO;
                IF NOT MISSING(CLNO) AND ((CLNO >= 35.2))
                 THEN DO;
                  _Node_ = 74;
                  _Leaf_ = 37;
                  P_BAD0 = 0;
                  P_BAD1 = 1;
                  V_BAD0 = 0;
                  V_BAD1 = 1;
                END;
                ELSE DO;
                  _Node_ = 73;
                  _Leaf_ = 36;
                  P_BAD0 = 1;
                  P_BAD1 = 0;
                  V_BAD0 = 1;
                  V_BAD1 = 0;
                END;
              END;
            END;
            ELSE DO;
              IF NOT MISSING(MORTDUE) AND ((MORTDUE >= 371808.48))
               THEN DO;
                _Node_ = 60;
                _Leaf_ = 24;
                P_BAD0 = 0;
                P_BAD1 = 1;
                V_BAD0 = 0;
                V_BAD1 = 1;
              END;
              ELSE DO;
                _Node_ = 59;
                _Leaf_ = 23;
                P_BAD0 = 0.96954023;
                P_BAD1 = 0.03045977;
                V_BAD0 = 0.96957123;
                V_BAD1 = 0.030428769;
              END;
            END;
          END;
        END;
      END;
    END;
  END;
END;
END;
****************************************************************;
******     END OF HP TREE (PROC HPSPLIT) SCORING CODE    ******;
****************************************************************;
